version: "3"
services:
  app:
    build: ./docker/react
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./react:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
  api:
    build: ./docker/gin
    depends_on:
      - mysql
    volumes:
      - ./api:/go/src/github.com/api/
    ports:
      - "8080:8080"
      - "2345:2345"
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    tty: true
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
